services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_URL: postgresql://user:pass@db:5432/db
    ports:
      - "5084:5000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:5000
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: sh -c "npm install && npm run dev"
#    command: sh -c "NODE_ENV=production npm run build && npm run start"
volumes:
  pgdata:
