"""Adjust columns

Revision ID: 0e0da6383848
Revises: cd93a38eadb1
Create Date: 2025-07-02 21:28:10.945898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0da6383848'
down_revision = 'cd93a38eadb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_key', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['url_key'])
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url_key')

    # ### end Alembic commands ###
